version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: hackathon-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: xintianhuang
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 