import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import apiRoutes from './routes/api';
import {initUsersTable} from './models/User';
dotenv.config();
const app=express();
const p=process.env.PORT||5000;
app.use(cors());
app.use(express.json());
app.get('/',(req,res)=>{res.json({message:'Backend API is running'});});
app.use('/api',apiRoutes);
const s=async()=>{try{await initUsersTable();console.log('Database initialized successfully');app.listen(p,()=>{console.log(`Server running on port ${p}`);});}catch(e){console.error('Failed to initialize database:',e);process.exit(1);}};
s(); 